version: '4.27.1'

services:
#1 configuration mysql image
    db:
        image: mysql
        restart: always
        environment:
            - MYSQL_USER=php_docker
            - MYSQL_PASSWORD=password # this should live in a env var
            - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
            - MYSQL_DATABASE=NEW_DB
        volumes:
            - mysql-data:/var/lib/mysql
#2 configuration myphpAdmin image
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_HOST=db
#3 configuration myphpserver image
    my-app:
        image: my-app:1.0
        ports:
        - 3000:3000

    
#4 local store data for persistance
volumes:
    mysql-data:
        driver: local